import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Color variant
 * Id: a29dedfc-6d2a-4f8b-be36-f14bcc6b25fb
 * Codename: color_variant
 */
export type ColorVariant = IContentItem<{
  /**
   * Variant (multiple_choice)
   * Required: false
   * Id: 51ee67ec-3888-4881-ae28-fdc582247a88
   * Codename: color_variant__variant
   *
   * Black - standard black variantInverted - grey backgroundDefault or not filled in - black
   */
  colorVariantVariant: Elements.MultipleChoiceElement;
}>;
