import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Color pattern
 * Id: 112331fb-6b9f-45a2-a1b4-82eb84d63754
 * Codename: color_pattern
 */
export type ColorPattern = IContentItem<{
  /**
   * Highlight style (multiple_choice)
   * Required: false
   * Id: 56a9ff57-a0a0-474f-8669-59cde31e8760
   * Codename: color_pattern__highlight_style
   */
  colorPatternHighlightStyle: Elements.MultipleChoiceElement;
}>;
