import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * XL heading
 * Id: 39fce50e-5866-42dc-85b6-245fda8a5589
 * Codename: xl_heading
 */
export type XLHeading = IContentItem<{
  /**
   * Size (multiple_choice)
   * Required: false
   * Id: e5e2c336-f1a2-4b4b-a2a5-de61b5a3dbd7
   * Codename: xl_heading__xl_heading
   *
   * The heading will get extra size - larger than our standard headings
   */
  xlHeadingXlHeading: Elements.MultipleChoiceElement;
}>;
