/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Kontent.ai
 * Environment: Content Purge
 * Project Id: 0dac1ee8-b38f-00c9-5946-f73983be41ea
 */
export const assetFolders = {};
