/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Kontent.ai
 * Environment: Rebrand - Hero Sections
 * Project Id: 3be27815-c01b-0097-9e60-d39c4ea7697b
 */
export const assetFolders = {};
