/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Kontent.ai
 * Environment: Redirects
 * Project Id: 309d7bd1-0401-0079-9200-1142d1035dcb
 */
export const collections = {};
