/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Kontent.ai
 * Environment: Thank you pages
 * Project Id: caa4aa0f-7278-0001-f9c9-2fb991327579
 */
export const webhooks = {};
