/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Kontent.ai
 * Environment: Events Migration
 * Project Id: f32ae34f-5e43-0068-5c0f-19f5e1bd6d9b
 */
export const webhooks = {};
