/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Kontent.ai
 * Environment: Redirects
 * Project Id: 309d7bd1-0401-0079-9200-1142d1035dcb
 */
export const workflows = {
  /**
   * UMLP
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  umlp: {
    codename: 'umlp',
    id: '49ae92ed-e94a-43ae-96e2-75077aad35e9',
    name: 'UMLP',
  },

  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: 0c00106a-3a23-4a8b-86d7-733999dc8f4e
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },

  /**
   * Careers
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  careers: {
    codename: 'careers',
    id: '42ed356d-77a0-4d2e-ab08-66fd6e8aa2fc',
    name: 'Careers',
  },

  /**
   * Events & webinars
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  events___webinars: {
    codename: 'events___webinars',
    id: '9f73b5ed-9911-49b2-9c00-a653b8cddb1e',
    name: 'Events & webinars',
  },
};
