import fs from 'fs'
import { MigrationModule } from '@kontent-ai/cli'
import { ManagementClient } from '@kontent-ai/management-sdk'

const slugs = [
  'announcing-the-2023-kontent-ai-mvps',
  'pre-rendered-server-rendered-or-hybrid-which-should-i-use',
  'stop-bothering-people-with-recaptcha-use-recaptcha',
  'avoid-production-errors-after-unexpected-content-model-changes',
  'comparison-of-jamstack-hosting-platforms-for-next-js',
  'avoid-vendor-lock-in-migrating-content-from-contentful-to-kontent',
  'gatsby-vs-next-gridsome-nuxt',
  'how-to-generate-rss-feed-in-next-js',
  'how-to-build-urls-and-handle-redirects-in-next-js',
  'how-to-handle-url-redirects-with-headless-cms',
  'how-to-start-a-b-testing-your-next-js-site',
  'how-kontent-ai-handles-disaster-recovery',
  'how-we-moved-from-zero-to-a-viable-ai-solution-with-headless-cms',
  'news-in-javascript-sdks',
  'how-to-run-scripts-before-every-build-on-next-js',
  'processing-webhooks-in-next-js',
  'react-or-vue-gatsby-or-gridsome',
  'build-jamstack-site-with-angular-and-scully',
  'defeat-technical-debt-on-a-modern-website-and-make-it-future-proof',
  'static-site-personalization',
  'kontent-ai-new-technology-mvps-2023',
  'how-to-test-cookies-using-end-to-end-tests-and-playwright',
  'how-to-benefit-from-const-assertion-in-your-typescript-code',
  'positive-the-perfect-blend-of-marketing-expertise-and-technical-ability',
  'introducing-luminary-a-leader-in-digital-experiences',
  'content-mapping',
  'how-leading-organizations-across-the-globe-exceed-customer-expectations',
  'actum-digital-empowering-organizations-with-digital-platforms',
  'addressing-localization-challenges-with-headless-content-management',
  'agile-personalization-strategy-for-success',
  'ai-based-auto-tagging-of-content-what-you-need-to-know',
  'kontent-ai-introduces-industry-s-first-cms-with-native-ai-capabilities',
  'machine-learning-how-to-ensure-labels-are-smart-not-lucky',
  'how-to-automatically-translate-content-using-webhooks',
  'best-404-page-examples',
  'best-landing-page-examples',
  'best-practices-for-writing-modular-content',
  'best-product-page-examples',
  'from-chaos-to-clarity-best-practices-for-content-taxonomy',
  'decoding-ai-success-tips-for-businesses-to-achieve-maximum-value-and-content-security',
  'governance-risk-and-compliance-at-kontent-ai',
  'how-we-implemented-security-in-a-modern-hybrid-workplace',
  'kontent-ai-expands-its-mvp-program-with-two-new-categories',
  'kontent-ai-joins-cybersecurity-tech-accord',
  'kontent-ai-launches-enhanced-partner-program',
  'looking-back-at-2023-trends-which-predictions-were-spot-on',
  'meet-community-minded-customer-centric-konabos',
  'navigating-the-privacy-landscape-how-kontent-ai-upholds-data-protection',
  'product-security-assurance-of-kontent-ai-a-trustworthy-foundation-for-content-management',
  'bridging-facts-and-stories-ai-enterprise-content-creation',
  'building-a-cloud-first-headless-cms',
  'headless-cms-site-built-in-one-day',
  'content-pipeline',
  'building-secure-software-kontent-ais-adoption-of-sbom',
  'building-your-custom-documentation-portal-when-you-already-have-two',
  'clearing-obsolete-cache-entries-with-webhooks',
  'cms-in-the-cloud-headless-cms',
  'common-misconceptions-about-generative-ai',
  'content-architecture',
  'content-federation-doesnt-deliver-unified-publishing',
  'content-governance',
  'content-strategy-using-chatgpt-with-a-headless-cms',
  'content-strategy-vs-content-marketing',
  'content-creation-process',
  'create-once-publish-everywhere-doing-cope-right',
  'how-to-quickly-build-a-headless-website-template',
  'defining-processes-and-procedures-to-support-content-operations',
  'how-to-disable-webhook-notifications-at-your-command',
  'how-to-build-a-strong-content-value-chain',
  'drive-success-with-an-engaging-customer-education-program',
  'edit-your-content-directly-from-website',
  '4-step-guide-to-effective-editorial-workflow',
  'effective-content-modeling',
  'shift-from-on-premise-platforms-to-headless-composable-saas-solutions',
  'emerging-best-practices-for-disclosing-ai-generated-content',
  'enterprise-content-governance-model-for-decision-making',
  'expand-content-reach-and-variety-with-structured-api-delivery',
  'five-benefits-of-reusing-content',
  'five-keys-to-prepping-content-like-a-top-chef',
  'flask-python-and-headless',
  'content-management-workflow',
  'graphql-support-in-kontent-for-devs',
  'start-2023-off-right-with-kontent-ai-s-yearly-release-wrap-up',
  'how-apis-can-support-your-content-strategy',
  'how-content-and-design-can-support-each-other',
  'how-content-and-ux-can-define-user-interaction-together',
  'how-content-is-a-game-changer-for-sports-organizations',
  'how-content-professionals-can-influence-organizational-change',
  'how-does-headless-cms-fit-into-an-aws-setup',
  'how-generative-ai-fits-into-content-development-processes',
  'how-many-content-types-do-you-need',
  'how-structured-content-is-different-in-headless-cmss',
  'designing-systems-to-support-content-and-ux-collaboration',
  'how-to-calculate-the-total-cost-of-ownership-of-cms',
  'how-to-choose-your-ai-vendor',
  'how-to-embed-guidance-to-better-govern-your-content',
  'leveraging-next-js-on-demand-isr',
  'how-to-include-the-right-details-in-your-content-model',
  'how-to-trigger-github-action-using-webhook-with-no-code',
  'how-to-write-headline',
  'hugo-and-headless-cms',
  'ignite-your-knowledge-new-learn-is-now-live',
  'image-transformations-master-responsive-design-with-kentico-cloud',
  'improve-the-modularity-of-your-next-user-experience-project',
  'improving-regulatory-compliance-in-financial-content-using-headless-cms',
  'join-the-brand-new-kentico-cloud-partner-program',
  'how-to-keep-it-stupid-simple-use-net-core-razor-pages',
  'kontent-ai-sdlc-in-agile-methodology',
  'kentico-kontent-achieves-soc-2-type-1-compliance',
  'kentico-kontent-completes-soc-2-type-2-examination',
  'kontent-ai-achieves-iso-27001-and-27017-certifications',
  'kontent-ai-appoints-new-senior-executives-and-joins-mach-alliance',
  'kontent-g2-fall-2022-enterprise-headless-cms-leader',
  '3-takeaways-from-kontent-ai-horizons-2022-in-london',
  'takeaways-from-kontent-ai-horizons-2022-in-new-york',
  'kontent-ai-horizons-2023-in-sydney-3-game-changing-insights',
  'kontent-ai-provides-hipaa-compliance-for-customers',
  'kontent-ai-joins-the-mach-alliance',
  'kontent-ai-recognized-in-gartner-market-guide-for-wcm-2022',
  'kontent-hates-wysiwyg',
  'kontent-transactable-offer-azure-marketplace',
  'kontent-loves-ab-tests',
  'kontent-loves-analytics',
  'kontent-loves-collaboration',
  'kontent-loves-landing-pages',
  'kontent-loves-marketing-automation',
  'kontent-loves-personalization',
  'kontent-loves-seo',
  'kontent-loves-social-media',
  'how-to-launch-a-beautiful-website-from-headless-web-templates',
  'lessons-learned-from-building-a-reliable-educational-portal',
  'leverage-technology-to-enhance-content-operations',
  'make-your-design-system-content-friendly',
  'make-your-rich-text-portable',
  'manage-content-and-assets-across-multiple-teams-and-channels',
  'manage-multiple-websites-efficiently-with-kontent-ai',
  'meet-mmt-the-digital-change-makers',
  'migrating-content-from-a-monolith-cms-to-a-headless-cms',
  'modular-ux-using-a-headless-cms',
  'seamless-multisite-management-with-web-spotlight',
  'top-2023-trends-in-mach-insights-from-mach-alliance-members',
  '3-inspiring-omnichannel-examples-you-should-know',
  '3-steps-to-rapidly-deploy-headless-single-page-app',
  '5-compelling-reasons-why-you-need-content-hub',
  '5-content-contribution-guidelines-keep-writers-motivated',
  '5-hallmarks-of-a-great-content-strategy',
  '5-effective-home-assistant-marketing-strategies',
  '5-social-media-tips-to-boost-your-business',
  '5-strategies-to-reach-unparalleled-return-on-content',
  '6-reasons-why-you-need-a-content-strategy',
  '7-tips-for-explaining-headless-cms-to-your-clients',
  'next-js-playwright-tests-github-action',
  'enrich-your-nuxt-3-site-with-headless-cms-content',
  'demystify-nuxt-target-mode-and-ssr-properties',
  'optimize-your-digital-project-timeline-with-headless-cms',
  'orchestration-in-personalization-matching-vs-directing',
  'inspired-or-stolen-how-to-stop-plagiarism-before-it-happens',
  'turn-insights-into-action-with-mission-control',
  'q1-2023-release-wrap-up-more-control-over-content-operations',
  'q2-2023-release-wrap-up-create-great-content-faster',
  'q3-2022-release-wrap-up',
  'q3-2023-release-wrap-up-achieve-an-unparalleled-return-on-content',
  'how-to-unlock-multilingual-capabilities-of-your-react-website',
  'emails-rounded-buttons-with-shadow-outlook',
  'emails-inline-tags-vertical-alignment-outlook',
  'emails-outlook-containers-rounded-courners',
  'emails-spacing-outlook-vertical-alignment-in-tables',
  'basics-implementing-testing-generated-emails',
  'scale-your-experience-connecting-content-and-design-modules',
  'searching-headless-content-with-algolia-rails-kontent-next-js',
  'security-as-a-business-enabler',
  'sending-push-notifications-from-kontent',
  'sourcebit-how-to-make-friends-with-various-data-sources-in-the-jamstack',
  'structured-content-as-building-blocks-of-the-user-experience',
  'structured-content-for-timelines',
  'structured-rich-text-rendering-in-mvc',
  'supply-chain-security-how-we-do-it-at-kontent-ai',
  'deployment-with-kontent-environments',
  'future-of-content-marketing',
  'structured-content',
  'the-rise-of-jamstack',
  'role-of-governance-in-preventing-content-debt',
  'evergreen-content',
  '7-stages-of-content-lifecycle',
  'thinklogic-solving-digital-problems-with-custom-solutions',
  'content-marketing-trends',
  'top-headless-cms-trends-you-cant-afford-to-miss-in-2023',
  'top-content-marketing-tools',
  'understanding-the-roi-of-content-production',
  'exporting-content-using-google-sheets',
  'dei-takeaways-from-women-in-mach-event',
  'bringing-radical-automation-to-content-operations',
  'kontent-ai-has-raised-40-million-in-growth-capital',
  'how-to-protect-sensitive-content-next-js-static-web-app',
  'unveiling-the-insights-key-takeaways-from-mach2',
  'using-content-models-for-custom-variations',
  'using-content-models-to-support-reuse',
  'using-new-kentico-cloud-content-management-api',
  'what-is-headless-cms',
  'what-is-static-website',
  'what-is-omnichannel',
  'role-of-content-management-in-digital-products',
  'where-is-my-wysiwyg-page-builder',
  'apis-are-the-future-of-content',
  'why-invest-in-generative-ai-for-content',
  'why-is-securing-ai-important',
  'why-manufacturers-rely-on-kontent-ai',
  'why-structured-writing-needs-structured-content',
  'why-the-dxp-experience-is-broken-and-how-to-build-a-better-one',
  'why-you-need-better-data-governance-and-security-from-your-headless-cms',
  'ditch-dita-and-adopt-headless',
  'why-you-should-use-figma-with-headless-cms',
  'kontent-ai-feature-wrap-up',
  'how-to-structure-blog-post',
  'website-content-ideas',
  'your-content-efficiency-needs-attention-generative-ai-can-help',
  'creating-print-and-pdf-content-with-a-headless-cms',
]

const titles = [
  'Announcing the 2023 Kontent.ai MVPs 🏆',
  'Pre-rendered, server-rendered, or hybrid?',
  'Stop bothering people with reCaptcha; use reCaptcha',
  'How to avoid production errors caused by content changes',
  'What’s the best place to host Next.js site?',
  'Avoid vendor lock-in: Migrating content from Contentful to Kontent',
  'Why is Next.js my ultimate choice over Gatsby, Gridsome, and Nuxt?',
  'How to generate RSS feed in Next.js',
  'How to build URLs and handle redirects in Next.js',
  'How to handle URL redirects when using a headless CMS',
  'How to implement AB tests in Next.js',
  'How Kontent.ai handles disaster recovery',
  'How we moved from zero to a viable AI solution with Kontent.ai',
  'The all new JavaScript SDKs—Should you upgrade?',
  'How to run scripts before every build on Next.js',
  'How to verify and process webhook notifications in Next.js',
  'How to decide between React and Vue? Gatsby and Gridsome?',
  'Build Jamstack site with Angular and Scully',
  'Defeat technical debt on a modern website and make it future-proof',
  'Personalizing static sites using Kontent and Pardot',
  'Kontent.ai welcomes two new Technology MVPs',
  'How to test cookies using end-to-end tests and Playwright',
  'How to benefit from const assertion in your TypeScript code?',
  'Meet client-centric and outcome-orientated, Positive',
  'Introducing Luminary, a leader in digital experiences',
  'A guide to effective content mapping for enhanced user engagement',
  'How leading organizations across the globe exceed customer expectations',
  'ACTUM Digital: Empowering organizations with digital platforms',
  'Addressing localization challenges with headless content management',
  'Agile personalization: A strategy for success',
  'AI-based auto-tagging of content: What you need to know',
  'Kontent.ai introduces industry’s first CMS with native AI capabilities',
  'Machine learning: How to ensure labels are smart, not lucky',
  'Automatic translation of content items using webhooks',
  'Best 404 page examples from our customers',
  'Best landing page design examples from our customers',
  'Best practices for writing modular content',
  'Best product page design examples in 2024',
  'From chaos to clarity: Best practices for content taxonomy',
  'Decoding AI success: Tips for businesses to achieve maximum value and content security',
  'Governance, risk, and compliance at Kontent.ai',
  'How we implemented security in a modern hybrid workplace',
  'Kontent.ai expands its MVP program with two new categories',
  'Kontent.ai joins Cybersecurity Tech Accord',
  'Kontent.ai launches enhanced Partner Program',
  'Looking back at 2023 trends: Which predictions were spot on?',
  'Meet community-minded, customer-centric Konabos',
  'Navigating the privacy landscape: How Kontent.ai upholds data protection',
  'Product security assurance of Kontent.ai: A trustworthy foundation for content management',
  'Bridging facts and stories: AI content creation',
  'Building a cloud-first headless CMS',
  'Building a website with headless CMS in just one day',
  'Building an agile content pipeline with a headless CMS',
  'Building secure software: Kontent.ai’s adoption of SBOM',
  'Building your custom documentation portal (when you already have two)',
  'Clearing obsolete cache entries with webhooks',
  "CMS in the cloud sucks and why it's time for a cloud-first headless CMS",
  'Common misconceptions about generative AI',
  'Content architecture: Building the digital blueprint',
  'Content federation doesn’t deliver unified publishing',
  'Content governance in the digital age',
  'Content strategy using ChatGPT with a headless CMS',
  'Content strategy vs content marketing: The key differences',
  'A deep dive into the content creation process',
  'Create once, publish everywhere: Doing COPE right',
  'How to quickly build a headless website template',
  'Defining processes and procedures',
  'Disable webhook notifications at your command',
  'How to build a strong content value chain',
  'Drive success with engaging customer education',
  'Edit your content directly from your website',
  '4-step guide to an effective editorial workflow',
  'Effective content modeling',
  'Shift from on-premise platforms to headless, composable SAAS solutions',
  'Emerging best practices for disclosing AI-generated content',
  'Enterprise content governance model',
  'Expand your content’s reach and variety with structured API delivery',
  'Five benefits of reusing content',
  'Five keys to prepping content like a top chef',
  'Headless, Python, and Flask: Massive flexibility in a microframework',
  'Demystifying the content management workflow',
  'What does native GraphQL support in Kontent bring for devs?',
  'Start 2023 off right with Kontent.ai’s release wrap-up',
  'How APIs can support your content strategy',
  'How content and design can support each other',
  'How content and UX define user interaction',
  'How content is a game changer for sports organizations',
  'How content professionals can influence organizational change',
  'How does headless CMS fit into an AWS setup?',
  'How generative AI fits into content development processes',
  'How many content types do you need?',
  'How structured content is different in headless CMSs',
  'Designing systems to support content and UX collaboration',
  'How to calculate the TCO of a content management system',
  'How to choose your AI vendor',
  'How to embed guidance to better govern your content',
  'How to improve cache efficiency and reduce costs with Next.js on-demand ISR',
  'How to include the right details in your content model',
  'How to trigger a GitHub action using a webhook',
  'How to write a powerful headline',
  'How to make the team happy with Hugo and headless',
  'Ignite your knowledge: New Learn is now live!',
  'Image transformations — Master responsive design with Kentico Cloud',
  'Improve the modularity of your next UX project',
  'Improving compliance in financial content with a headless CMS',
  'Join the brand new Kentico Cloud partner program',
  'How to keep it stupid simple: Use .NET Core Razor Pages',
  'Kontent.ai SDLC in agile methodology',
  'Kontent.ai achieves SOC 2 Type 1 compliance',
  'Kontent.ai completes SOC 2 Type 2 examination',
  'Kontent.ai achieves ISO 27001 and 27017 security certifications',
  'Kontent.ai appoints new senior executives and joins MACH Alliance to support global expansion',
  'Kontent.ai named an enterprise headless CMS leader on G2',
  '3 takeaways from Kontent.ai Horizons 2022 in London',
  'Takeaways from Kontent.ai Horizons 2022 in NYC',
  'Kontent.ai Horizons 2023 in Sydney: 3 game-changing insights',
  'Kontent.ai provides HIPAA compliance for customers',
  'Kontent.ai joins the MACH Alliance',
  'Kontent.ai recognized in 2022 Gartner® Market Guide for Web Content Management',
  'Kontent.ai hates: WYSIWYG',
  'Kontent.ai is now a transactable offer on Azure Marketplace',
  'Kontent.ai loves: A/B tests',
  'Kontent.ai loves: Analytics',
  'Kontent.ai loves: Collaboration',
  'Kontent.ai loves: Landing pages',
  'Kontent.ai loves: Marketing automation',
  'Kontent.ai loves: Personalization',
  'Kontent.ai loves: SEO',
  'Kontent.ai loves: Ads and social media',
  'How to launch a beautiful website from headless web templates',
  'Lessons learned from building a reliable educational portal',
  'Leverage technology to enhance content operations',
  'Make your design system content-friendly',
  'Make your rich text portable',
  'Manage content and assets across multiple teams and channels',
  'Manage multiple websites efficiently with Kontent.ai',
  'Meet MMT, the digital change makers',
  'Migrating content from a monolith CMS to a headless CMS',
  'Modular UX using a headless CMS',
  'Seamless multisite management with Web Spotlight',
  'Top 2023 trends in MACH: Insights from MACH Alliance members',
  '3 inspiring omnichannel examples you should know',
  '3 steps to rapidly deploy a headless single page application',
  '5 compelling reasons why you need a content hub',
  '5 content contribution guidelines to keep your writers motivated',
  '5 hallmarks of a great content strategy',
  '5 highly effective home assistant marketing strategies',
  '5 social media tips to boost your business',
  '5 strategies to reach an unparalleled return on content',
  '6 reasons why you need a content strategy',
  '7 tips for explaining headless CMS to your clients',
  'How to use Playwright with Next.js, Vercel, and GitHub',
  'Enrich your Nuxt 3 site with headless CMS content',
  'Demystify Nuxtʼs target, mode, and SSR properties',
  'Optimize your web project timeline with headless CMS',
  'Orchestration in personalization: Matching vs. directing',
  'Inspired or stolen? How to stop plagiarism before it happens',
  'Turn insights into action with Mission Control',
  'Q1 2023 release wrap-up: More control over content operations',
  'Q2 2023 wrap-up: Create great content, faster',
  'Q3 2022 Kontent.ai release wrap-up',
  'Q3 2023 release wrap-up: Achieve an unparalleled return on content',
  'How to improve your project with multilingual capabilities',
  'Implementing emails in 2021: Rounded buttons in Outlook',
  'Implementing emails in 2021: Inline tags & vertical alignment',
  'Adding rounded corners to containers in Outlook',
  'Implementing emails 2021: Spacing and vertical alignment in tables',
  'Implementing emails in 2021: Basics & testing',
  'Scale your experience: Connecting content & design modules',
  'Searching headless content with Algolia, Rails, Kontent & Next.js',
  'Security as a business enabler: Building trust and empowering users',
  'Sending push notifications from Kontent',
  'How to make friends with various datasources in the Jamstack?',
  'Structured content as building blocks of the user experience',
  'Structured content for timelines',
  'Structured rich text rendering in MVC',
  'Supply chain security and how we do it at Kontent.ai',
  'Taking the fear out of deployments with environments',
  'The future of content marketing | 5 trends to expect in 2023',
  'The power and potential of structured content',
  'The rise of JAMstack',
  'Role of governance in preventing content debt',
  'The ultimate guide to evergreen content',
  'The 7 stages of the content lifecycle',
  'Thinklogic: Solving digital problems with custom solutions',
  'Top 7 content marketing trends in 2022',
  'Top headless CMS trends you can’t afford to miss in 2023',
  'Top 10 content marketing tools you need',
  'Understanding the ROI of content production',
  'Exporting content using Google Sheets',
  'Takeaways from the first-ever Women in MACH event',
  'Bringing radical automation to content operations',
  'Kontent.ai has raised $40 million in growth capital',
  'Protect sensitive content in Next.js static web app',
  'Unveiling the insights: Key takeaways from MACH2',
  'Using content models for custom variations',
  'Using content models to support reuse',
  'Using the new Kentico Cloud content management API',
  'Headless CMS explained in 5 minutes',
  'What is a static website and how to create one',
  'What are omnichannel experiences? Benefits, trends, examples',
  'What’s the role of content management in digital products?',
  'Where is my WYSIWYG page builder?',
  'Why APIs are the future of content',
  'Why invest in generative AI for content?',
  'Why is securing AI important',
  'Why manufacturers rely on Kontent.ai',
  'Why structured writing needs structured content',
  'Why the DXP experience is broken and how to build a better one',
  'Why you need better data governance and security from your headless CMS',
  'Why you should ditch DITA and adopt headless instead',
  'Why you should use Figma with headless CMS',
  'Explore the benefits of new Kontent.ai features',
  '7+1 steps to structure a blog post',
  '9 website content ideas for your business',
  'Your content efficiency needs attention – generative AI can help',
  'Creating print and PDF content with a headless CMS',
]

const migration: MigrationModule = {
  order: 14,
  run: async (apiClient: ManagementClient) => {
    const items = slugs.map((slug, index) => {
      return {
        slug,
        title: titles[index],
      }
    })

    const filePath = './src/data/blog_sentence_case_slugs.json'
    fs.writeFileSync(filePath, JSON.stringify({ slugs: items }, null, 2))
  },
}

export default migration
