import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Hero } from '../content-type-snippets/hero';
import { UmlpElementFeaturedCustomerSuccessStoriesModel } from './UmlpElementFeaturedCustomerSuccessStoriesModel';
import { UmlpElementLogosCustomModel } from './UmlpElementLogosCustomModel';
import { UmlpElementG2BadgesModel } from './UmlpElementG2BadgesModel';
import { CaseStudyModel } from './CaseStudyModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Customer success home
 * Id: ce4e4ccd-5ff4-4c2d-b384-fd17b8d1f6bb
 * Codename: case_studies_page
 */
export type CaseStudiesPageModel = IContentItem<{
  /**
   * Featured stories (modular_content)
   * Required: true
   * Id: 232230ef-e816-4d35-bb19-3a75d11245c3
   * Codename: featured_stories
   */
  featuredStories: Elements.LinkedItemsElement<UmlpElementFeaturedCustomerSuccessStoriesModel>;

  /**
   * Logo slider (modular_content)
   * Required: true
   * Id: cdabaa09-aa87-4d39-b118-25260ec40d48
   * Codename: logo_slider
   */
  logoSlider: Elements.LinkedItemsElement<UmlpElementLogosCustomModel>;

  /**
   * G2 Awards (modular_content)
   * Required: false
   * Id: 4be5d4b2-cb4e-4f03-8f22-aa0535e425d3
   * Codename: g2_awards
   */
  g2Awards: Elements.LinkedItemsElement<UmlpElementG2BadgesModel>;

  /**
   * Title (text)
   * Required: false
   * Id: 455f8b4b-3f22-9406-b505-f78410f14dba
   * Codename: title
   *
   * !OBSOLETE!
   */
  title: Elements.TextElement;

  /**
   * No case study found message (text)
   * Required: false
   * Id: 473ca13f-40f4-4c58-b6a0-a21330bcd760
   * Codename: no_case_study_found_message
   */
  noCaseStudyFoundMessage: Elements.TextElement;

  /**
   * Empty filter fallback case studies (modular_content)
   * Required: true
   * Id: 3bca5d88-2200-49e5-8e8e-953e4975029f
   * Codename: empty_filter_fallback_case_studies
   */
  emptyFilterFallbackCaseStudies: Elements.LinkedItemsElement<CaseStudyModel>;

  /**
   * Metadata title (text)
   * Required: false
   * Id: eb743d80-e2fa-85fb-c4c1-b3f68e7ba3a8
   * Codename: metadata_title
   */
  metadataTitle: Elements.TextElement;

  /**
   * Metadata description (text)
   * Required: false
   * Id: 8dc51588-05c8-c438-0407-6b1b5bdf04b9
   * Codename: metadata_description
   */
  metadataDescription: Elements.TextElement;

  /**
   * Metadata image (asset)
   * Required: true
   * Id: af7c5992-ce21-4fa7-b480-e2c4e2fd0286
   * Codename: metadata_image
   */
  metadataImage: Elements.AssetsElement;

  /**
   * CTA Section (modular_content)
   * Required: false
   * Id: aa647290-79c1-4a76-9a92-7c110acaf094
   * Codename: cta_section
   */
  ctaSection: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  Hero &
  SitemapMetadata;
