import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { EventDateModel } from './EventDateModel';
import { AuthorModel } from './AuthorModel';
import { PartnerModel } from './PartnerModel';
import { WebinarEventTopicModel } from './WebinarEventTopicModel';
import { EventsAndWebinarsThankYouPageModel } from './EventsAndWebinarsThankYouPageModel';
import { Metadata } from '../content-type-snippets/metadata';
import { AddressModel } from './AddressModel';
import { TimeZoneModel } from './TimeZoneModel';
import { EventTalkModel } from './EventTalkModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Event
 * Id: ae6cab38-500c-4fbd-a620-4456afd16e98
 * Codename: event
 */
export type EventModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: c2f39b6f-ec7c-4c80-847b-a481898ebd35
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Overview (rich_text)
   * Required: true
   * Id: e24ea59f-12e8-488b-ba7a-c2bc12e5fd35
   * Codename: overview
   *
   * Short summary of the event (displayed on the event card)
   */
  overview: Elements.RichTextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 2617b0ad-a391-42de-8bb3-41fbf22c0737
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Dates (modular_content)
   * Required: true
   * Id: b0174a90-efce-416d-abb4-8fbad9d2fa1b
   * Codename: dates
   */
  dates: Elements.LinkedItemsElement<EventDateModel>;

  /**
   * Speakers (modular_content)
   * Required: false
   * Id: 11550580-9e14-4659-9c54-1a3c02bfe50d
   * Codename: speakers
   *
   * Speakers for this event
   */
  speakers: Elements.LinkedItemsElement<AuthorModel>;

  /**
   * Partnership (modular_content)
   * Required: false
   * Id: 66f6bea7-5d85-4e25-87bb-e0e40856b3d8
   * Codename: partnership
   *
   * Partner for this event
   */
  partnership: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Wrap Up (rich_text)
   * Required: false
   * Id: b10493c2-1822-44e7-ad29-c63138ff6955
   * Codename: wrap_up
   *
   * Post-event wrap-up
   */
  wrapUp: Elements.RichTextElement;

  /**
   * Topic (modular_content)
   * Required: false
   * Id: e329cbc1-5c5a-4e92-b10d-811c7c451efc
   * Codename: topic
   */
  topic: Elements.LinkedItemsElement<WebinarEventTopicModel>;

  /**
   * Card image (asset)
   * Required: true
   * Id: c8227e44-8129-44b4-87e3-cafe9663bdde
   * Codename: card_image
   *
   * A smaller image used for the card on the webinars page.DISCLAIMER: If the event is used in the featured section at /events-and-webinars as the HORIZONTAL card - you need to use 2 images. 1st image will be used for a standard card (on smaller viewports and in the standard listing) and the 2nd image (narrower) will be used for the horizontal card.
   */
  cardImage: Elements.AssetsElement;

  /**
   * Image strip image (asset)
   * Required: false
   * Id: 51c67211-7995-41a4-b5bd-f3316c38acff
   * Codename: image_strip_image
   *
   * Optional full-width image black and white image used on the webinar detail page.
   */
  imageStripImage: Elements.AssetsElement;

  /**
   * Hero image (asset)
   * Required: false
   * Id: 52432d81-fdae-49fe-bc82-6b522e6da05a
   * Codename: hero_image
   *
   * Optional hero image used on the webinar detail page with a petal (if there's no image strip). If no image strip or hero image is provided, only the petal will be shown.
   */
  heroImage: Elements.AssetsElement;

  /**
   * Recording poster (asset)
   * Required: false
   * Id: 13b5858c-27bf-4418-b79e-f942ed777099
   * Codename: recording_poster
   */
  recordingPoster: Elements.AssetsElement;

  /**
   * Registration URL (text)
   * Required: false
   * Id: b269ac44-2ca2-44a6-8497-2f9547b2dc7e
   * Codename: registration_url
   *
   * Used for external webinars
   */
  registrationUrl: Elements.TextElement;

  /**
   * Recording URL (text)
   * Required: false
   * Id: a14016b0-4592-4071-9209-864ad4686f4f
   * Codename: recording_url
   *
   * Recording/video from a past event. Use this format: https://www.youtube.com/watch?v=J3XRGtUeGXc
   */
  recordingUrl: Elements.TextElement;

  /**
   * URL Slug (url_slug)
   * Required: true
   * Id: f80bdae2-ad52-4a59-a4d7-882b77f7f53d
   * Codename: url_slug
   *
   * URL slug for this webinar (e.g. /horizons-2022)
   */
  urlSlug: Elements.UrlSlugElement;

  /**
   * Previously used URL slugs (custom)
   * Required: false
   * Id: fe03bffd-0f33-4503-bac6-836dad82d8b9
   * Codename: previously_used_url_slugs
   */
  previouslyUsedUrlSlugs: Elements.CustomElement;

  /**
   * Form heading (text)
   * Required: false
   * Id: b3571d96-7ec5-4785-a4e4-400f0dd4169a
   * Codename: form_heading
   */
  formHeading: Elements.TextElement;

  /**
   * Button text (text)
   * Required: false
   * Id: 7bc337d4-7186-4c99-8e10-8fff9442530c
   * Codename: button_text
   */
  buttonText: Elements.TextElement;

  /**
   * Thank You Page (modular_content)
   * Required: true
   * Id: 655b65af-c3fe-417c-8851-6e7459837996
   * Codename: thank_you_page
   */
  thankYouPage: Elements.LinkedItemsElement<EventsAndWebinarsThankYouPageModel>;

  /**
   * Schema.org description (text)
   * Required: false
   * Id: 95c3fa63-2e41-48d1-a03c-6da4950bf93f
   * Codename: schema_org_description
   */
  schemaOrgDescription: Elements.TextElement;

  /**
   * Location (text)
   * Required: true
   * Id: ecb3cc7f-72af-4dc6-b481-c6d336fc77af
   * Codename: location
   */
  location: Elements.TextElement;

  /**
   * Start Date and Time (date_time)
   * Required: false
   * Id: db0c6fb4-dc09-4282-a6c8-6fc4fc1f4f21
   * Codename: start_date_and_time
   */
  startDateAndTime: Elements.DateTimeElement;

  /**
   * End Date and Time (date_time)
   * Required: false
   * Id: 088ae12f-89db-41ed-8a47-2309fb21ffa3
   * Codename: end_date_and_time
   */
  endDateAndTime: Elements.DateTimeElement;

  /**
   * Venue (modular_content)
   * Required: false
   * Id: 6832c555-8427-4921-bc81-fcef0bf754ce
   * Codename: venue
   */
  venue: Elements.LinkedItemsElement<AddressModel>;

  /**
   * Time zone (modular_content)
   * Required: true
   * Id: c04f387d-8cf1-4d0c-b0a0-3d98baed518d
   * Codename: time_zone
   */
  timeZone: Elements.LinkedItemsElement<TimeZoneModel>;

  /**
   * Type (multiple_choice)
   * Required: true
   * Id: 2f17b6c4-7364-4db2-81ef-ae2c37478c06
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;

  /**
   * Registration open (multiple_choice)
   * Required: true
   * Id: af714e5e-0195-4dfd-9e87-828bf6d1ba93
   * Codename: registration_open
   */
  registrationOpen: Elements.MultipleChoiceElement;

  /**
   * Agenda (modular_content)
   * Required: false
   * Id: 87845d05-2eb6-4324-9664-81273e88397a
   * Codename: agenda
   */
  agenda: Elements.LinkedItemsElement<EventTalkModel>;

  /**
   * Pardot URL (text)
   * Required: false
   * Id: b7d1b423-e5ba-4aef-b889-692eff4a9491
   * Codename: pardot_url
   *
   * Pardot iframe URL, ie. https://tracker.kontent.ai/l/849473/2020-03-04/2kny
   */
  pardotUrl: Elements.TextElement;
}> &
  Metadata;
