import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UMLPContent } from '../content-type-snippets/umlp_content';
import { Metadata } from '../content-type-snippets/metadata';
import { Opengraph } from '../content-type-snippets/opengraph';
import { ReleaseProjects } from '../taxonomies/release_projects';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Home page
 * Id: f54e0c26-84ba-41eb-8144-6189f81e1e68
 * Codename: home_page
 */
export type HomePageModel = IContentItem<{
  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 007b6fe2-c71e-49b5-a115-2219c4a0771a
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}> &
  UMLPContent &
  Metadata &
  Opengraph &
  SitemapMetadata;
