import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { NewsletterNewsModel } from './NewsletterNewsModel';
import { NewsletterShortNewsModel } from './NewsletterShortNewsModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Newsletter
 * Id: f6cd0fcd-182e-4733-8243-e1a842be3088
 * Codename: newsletter
 */
export type NewsletterModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: fec7a561-1414-4e21-a161-e8162bd43227
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Intro (rich_text)
   * Required: true
   * Id: b76e2da4-a23f-4af6-a3dd-6899380b5648
   * Codename: intro
   */
  intro: Elements.RichTextElement;

  /**
   * Main News (modular_content)
   * Required: false
   * Id: 452ce10f-8e11-4f4e-8a08-6a0608989c42
   * Codename: main_news
   */
  mainNews: Elements.LinkedItemsElement<
    NewsletterNewsModel | NewsletterShortNewsModel
  >;

  /**
   * Event News (modular_content)
   * Required: false
   * Id: a2eb079e-5414-4a82-a76a-27a3d15aba7e
   * Codename: event_news
   */
  eventNews: Elements.LinkedItemsElement<
    NewsletterNewsModel | NewsletterShortNewsModel
  >;

  /**
   * Content News (modular_content)
   * Required: false
   * Id: 7ae3ca50-e128-4a8a-9714-c08c09e88552
   * Codename: content_news
   */
  contentNews: Elements.LinkedItemsElement<
    NewsletterNewsModel | NewsletterShortNewsModel
  >;

  /**
   * Dev News (modular_content)
   * Required: false
   * Id: 3cf1bcaa-1d3f-409f-8960-99e482c52d7d
   * Codename: dev_news
   */
  devNews: Elements.LinkedItemsElement<
    NewsletterNewsModel | NewsletterShortNewsModel
  >;

  /**
   * Things to celebrate (modular_content)
   * Required: false
   * Id: 1843ce79-464b-42cc-bd11-4c100235a52f
   * Codename: things_to_celebrate
   */
  thingsToCelebrate: Elements.LinkedItemsElement<
    NewsletterNewsModel | NewsletterShortNewsModel
  >;
}>;
