import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * News
 * Id: a3d50a84-3d7b-4a77-a136-289102882d98
 * Codename: news
 */
export type NewsModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 61e31920-aed9-43c5-ad22-0c99c69e496e
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 31862f1d-c94e-47b7-9b8c-4eac60766ddb
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: 272537f5-bdd6-4aa8-aff1-c9374db23704
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 7fbf887b-8ed7-4c01-a45d-16c5f106dedf
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;
}>;
