import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Redirect
 * Id: c74e3c8b-f31d-43c8-9769-1e7fd419c5f7
 * Codename: redirect_c74e3c8
 */
export type RedirectC74e3c8Model = IContentItem<{
  /**
   * From (text)
   * Required: true
   * Id: 39296505-5ee9-417a-87f5-fb5956169665
   * Codename: from
   */
  from: Elements.TextElement;

  /**
   * To (text)
   * Required: false
   * Id: 3145cc15-3933-4875-9f07-a88b809e63c7
   * Codename: to
   */
  to: Elements.TextElement;

  /**
   * Permanent (multiple_choice)
   * Required: true
   * Id: 8db554b9-34cb-4430-8679-94ac48c2aefd
   * Codename: permanent
   */
  permanent: Elements.MultipleChoiceElement;
}>;
