import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Hero } from '../content-type-snippets/hero';
import { ResourceModel } from './ResourceModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Resource page
 * Id: 45a69f1b-378e-43b9-9969-8b49c27a7462
 * Codename: resource_page
 */
export type ResourcePageModel = IContentItem<{
  /**
   * Featured resource (modular_content)
   * Required: true
   * Id: dd10f207-5b5a-4b6b-8569-ed5b889c62b9
   * Codename: featured_resource
   */
  featuredResource: Elements.LinkedItemsElement<ResourceModel>;

  /**
   * Image (asset)
   * Required: true
   * Id: 563092e0-b7d5-4c5e-b9b2-20b15936120f
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * No resources found message (text)
   * Required: false
   * Id: ded744d7-40ff-4161-9c16-6bce52ef19fc
   * Codename: no_resources_found_message
   */
  noResourcesFoundMessage: Elements.TextElement;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: ed063afc-e6e1-4cf6-acc6-07855e760b77
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  Hero &
  Metadata &
  SitemapMetadata;
