import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ClientActionOpenFaqModel } from './ClientActionOpenFaqModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Shared content
 * Id: 97f6a05f-3af4-43f3-ae49-c81765c676d2
 * Codename: shared_content
 */
export type SharedContentModel = IContentItem<{
  /**
   * Text (text)
   * Required: true
   * Id: 03f7a366-e475-52cd-ba27-d4c797029d81
   * Codename: text
   */
  text: Elements.TextElement;

  /**
   * Open in new tab (multiple_choice)
   * Required: false
   * Id: 383d1df5-1ad1-4676-878a-96e15916633d
   * Codename: open_in_new_tab
   */
  openInNewTab: Elements.MultipleChoiceElement;

  /**
   * URL (text)
   * Required: true
   * Id: f19304e0-1922-3d4b-12aa-b0d595253d46
   * Codename: url
   */
  url: Elements.TextElement;

  /**
   * Variant (multiple_choice)
   * Required: false
   * Id: 0e546b01-dc57-425e-9d38-c3ac5684f1bb
   * Codename: variant
   *
   * *This field can be left empty* - Only works for btns embedded in a RichText field. Please use with caution and only when necessary.
   */
  variant: Elements.MultipleChoiceElement;

  /**
   * Alignment (multiple_choice)
   * Required: false
   * Id: c8c775a5-a7ed-43aa-8698-70cd6db9f4d1
   * Codename: alignment
   *
   * *This field can be left empty* - Only works for btns embedded in a RichText field
   */
  alignment: Elements.MultipleChoiceElement;

  /**
   * Tracking code (text)
   * Required: false
   * Id: edbeba1e-f4fa-9f4f-ef41-43de71fa04dc
   * Codename: tracking_code
   *
   * Tracking code for Google Analytics. Should be entered as parameter of dataLayer.push function including curly brackets, e.g.: {'event': 'Menu_ProductSubmenu_Product'}
   */
  trackingCode: Elements.TextElement;

  /**
   * Client actions (modular_content)
   * Required: false
   * Id: c55437ed-2afc-4871-6dba-f60e0b79982a
   * Codename: client_actions
   */
  clientActions: Elements.LinkedItemsElement<ClientActionOpenFaqModel>;

  /**
   * Text (text)
   * Required: false
   * Id: d33da560-9db9-4e25-88ca-9ae4d3159f4c
   * Codename: personalization_text
   */
  personalizationText: Elements.TextElement;

  /**
   * URL (text)
   * Required: false
   * Id: e0a46a90-d968-4494-a92c-738373c81ee4
   * Codename: personalization_url
   */
  personalizationUrl: Elements.TextElement;

  /**
   * Tracking code (text)
   * Required: false
   * Id: 95054549-05d9-40c1-a3db-527b0c713b60
   * Codename: personalization_tracking_code
   */
  personalizationTrackingCode: Elements.TextElement;

  /**
   * User type (multiple_choice)
   * Required: false
   * Id: a2e02ac6-939d-4bca-91fd-de03c2568003
   * Codename: user_type
   */
  userType: Elements.MultipleChoiceElement;
}>;
