import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Kontent.ai Feature Showcase
 * Id: b81f15da-529d-44f4-8326-1d72af94a0fa
 * Codename: umlp_element___kontent_ai_feature_showcase
 */
export type UmlpElementKontentAiFeatureShowcaseModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 4c7c045e-fe86-4912-90fe-c304d82b32aa
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Cards (modular_content)
   * Required: true
   * Id: 07f94c93-4eae-4da6-84d4-048c00b37a2d
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<ModularItemCardElementModel>;
}>;
