import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PresentationalCardModel } from './PresentationalCardModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Presentational cards section
 * Id: 3ec42ddd-b474-49aa-8a8f-8544957d4f36
 * Codename: umlp_element__presentational_cards_section
 */
export type UmlpElementPresentationalCardsSectionModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: d72fd8b1-c864-4df7-ae2c-0ef8982f2dd5
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Cards (modular_content)
   * Required: true
   * Id: 894b7e83-2fc1-4917-82d9-3ec0b74c2c27
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<PresentationalCardModel>;

  /**
   * Theme (multiple_choice)
   * Required: true
   * Id: e17e61cb-9a1a-409e-82cf-a04b65883c43
   * Codename: theme
   *
   * Background color of the section. White is default.
   */
  theme: Elements.MultipleChoiceElement;
}>;
