import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementStatsSectionStatModel } from './UmlpElementStatsSectionStatModel';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Stats Section
 * Id: c991268d-2bd4-4e58-9e90-266749e3b837
 * Codename: umlp_element___stats_section
 */
export type UmlpElementStatsSectionModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: af9d264e-9118-4dc1-ba61-0f5d4e62f697
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: d2367c5c-e782-44ac-b02a-dbd06d121b5b
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Stats (modular_content)
   * Required: true
   * Id: 9b41bf4e-5619-44ca-b135-7a5d12398d13
   * Codename: stats
   */
  stats: Elements.LinkedItemsElement<UmlpElementStatsSectionStatModel>;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: d8f9a728-eb04-4be2-a959-1f50b331ddc6
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;
}>;
