import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Content flow infographic
 * Id: e8ebb641-5d18-46ac-b667-71a4f9e5ceda
 * Codename: umlp_element___content_flow_infographic
 */
export type UmlpElementContentFlowInfographicModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: true
   * Id: c3b109d6-308f-47bb-8fe2-03a4dffb4c26
   * Codename: heading__rich
   *
   * New heading field which allows text highlighting
   */
  headingRich: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: 24761ee6-a79c-4c78-ae71-75167b3c9103
   * Codename: text
   */
  text: Elements.RichTextElement;
}>;
