import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementExpandableSliderSlideModel } from './UmlpElementExpandableSliderSlideModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Expandable Slider
 * Id: dafca388-c4a6-4964-9d8e-9cd6539e085f
 * Codename: umlp_element___expandable_slider
 */
export type UmlpElementExpandableSliderModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: true
   * Id: fcb30778-f179-49e1-9665-2c5489fecee7
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Slides (modular_content)
   * Required: true
   * Id: 45f45290-33be-41a3-96c1-cb1a598ef943
   * Codename: slides
   */
  slides: Elements.LinkedItemsElement<UmlpElementExpandableSliderSlideModel>;
}>;
