import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { LogoModel } from './LogoModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Static Logos
 * Id: 36a8860e-99b7-4096-9d73-fff045b28bf5
 * Codename: umlp_element___static_logos
 */
export type UmlpElementStaticLogosModel = IContentItem<{
  /**
   * Logos (modular_content)
   * Required: true
   * Id: c70f3210-db85-48c9-8896-ad854b66c5c3
   * Codename: logos
   */
  logos: Elements.LinkedItemsElement<LogoModel>;
}>;
