import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ColorPattern } from '../content-type-snippets/color_pattern';
import { XLHeading } from '../content-type-snippets/xl_heading';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Hero Simple
 * Id: 441fea46-a441-4fd8-8261-aed93dc56cf6
 * Codename: umlp_element___hero_simple
 */
export type UmlpElementHeroSimpleModel = IContentItem<{
  /**
   * OUTDATED - Heading (text)
   * Required: true
   * Id: 767766e2-39c5-4648-a61a-7d3824dddd07
   * Codename: heading
   *
   * Only in place for the current version of k.ai. For any new elements of the REBRANDED website, use the rich element below.
   */
  heading: Elements.TextElement;

  /**
   * Heading (rich_text)
   * Required: true
   * Id: 3654159d-7a7c-473f-9797-3b51e542e32d
   * Codename: heading_rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: ca211f03-7d20-4050-91cd-f347b2714773
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Buttons (modular_content)
   * Required: false
   * Id: 7e5702e1-1341-4d86-bdc5-627bedfada12
   * Codename: buttons
   */
  buttons: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Alignment (multiple_choice)
   * Required: true
   * Id: 403ac096-3e15-44c6-bf4b-877e963fa2f3
   * Codename: alignment
   */
  alignment: Elements.MultipleChoiceElement;
}> &
  ColorPattern &
  XLHeading;
