import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - TCO Calculator Form
 * Id: a2768f19-e9ff-47cf-8ce9-b36e34885840
 * Codename: umlp_element___tco_calculator_form
 */
export type UmlpElementTcoCalculatorFormModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: true
   * Id: 601e497c-e048-4821-babe-05fb6f9ac988
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;
}>;
