import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - CTA Strip with Image
 * Id: 0d7413cd-622b-41b5-8896-4a1bc20ce7f3
 * Codename: umlp_element___cta_strip_with_image
 */
export type UmlpElementCtaStripWithImageModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: true
   * Id: 1f2267c6-f8b5-4c5c-9254-24e0cae0b369
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 7367c765-182f-4882-b9b2-f84cb037a37a
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * CTA button (modular_content)
   * Required: false
   * Id: 37d04894-0e0d-420e-ac5c-4cac9261fee6
   * Codename: cta_button
   */
  ctaButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Image (asset)
   * Required: true
   * Id: bdb2cfc6-7385-43cd-93f3-e7850d74c9b9
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Image position (multiple_choice)
   * Required: true
   * Id: 48dca5de-c1ad-4d6a-bb61-7aa79855b5d2
   * Codename: image_position
   */
  imagePosition: Elements.MultipleChoiceElement;
}>;
