import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementStatsSectionStatModel } from './UmlpElementStatsSectionStatModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Stats Section
 * Id: c991268d-2bd4-4e58-9e90-266749e3b837
 * Codename: umlp_element___stats_section
 */
export type UmlpElementStatsSectionModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: af9d264e-9118-4dc1-ba61-0f5d4e62f697
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Subheading (text)
   * Required: true
   * Id: fa32bc5e-3fa3-4b05-91bf-5e6d70f35ace
   * Codename: subheading
   */
  subheading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: d2367c5c-e782-44ac-b02a-dbd06d121b5b
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Stats heading (text)
   * Required: false
   * Id: 20177fc8-29c0-4243-a55c-de5d0cb7eb06
   * Codename: stats_heading
   *
   * Optional heading above the stats
   */
  statsHeading: Elements.TextElement;

  /**
   * Stats (modular_content)
   * Required: true
   * Id: 9b41bf4e-5619-44ca-b135-7a5d12398d13
   * Codename: stats
   */
  stats: Elements.LinkedItemsElement<UmlpElementStatsSectionStatModel>;
}>;
