import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementImageCarouselSlideModel } from './UmlpElementImageCarouselSlideModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Image Carousel
 * Id: 7b840b2c-0180-4b77-a27d-45cd569de840
 * Codename: umlp_element___image_carousel
 */
export type UmlpElementImageCarouselModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: be09f0fb-747d-45cd-b351-201432a53826
   * Codename: heading
   *
   * Optional heading
   */
  heading: Elements.RichTextElement;

  /**
   * Slides (modular_content)
   * Required: true
   * Id: 093e15a6-a9fa-4012-b062-3194988f3ec4
   * Codename: slides
   */
  slides: Elements.LinkedItemsElement<UmlpElementImageCarouselSlideModel>;
}>;
