import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Expandable Grid - Cell
 * Id: 24cd35d6-d761-4c17-8cc3-2f9396b21402
 * Codename: umlp_element___expandable_grid___cell
 */
export type UmlpElementExpandableGridCellModel = IContentItem<{
  /**
   * Icon (custom)
   * Required: false
   * Id: f3b84366-799f-4e70-8042-bee295b62096
   * Codename: icon
   *
   * If icon is not selected, checkmark icon will be displayed
   */
  icon: Elements.CustomElement;

  /**
   * Text (text)
   * Required: true
   * Id: ba09d6a3-04f8-4703-b197-56e29bfc8f6f
   * Codename: text
   */
  text: Elements.TextElement;
}>;
