import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { BubbleModel } from './BubbleModel';
import { ColorVariant } from '../content-type-snippets/color_variant';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Content Bubbles Grid
 * Id: 1832fc7a-cc5e-40b2-b0a0-7da8790b1960
 * Codename: umlp_element___content_bubbles_grid
 */
export type UmlpElementContentBubblesGridModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 08473d74-a0c4-48f1-b085-77c5a5f37fab
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: 40f441db-bc58-4ca8-ab47-bc99f278e4dd
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Bubbles (modular_content)
   * Required: true
   * Id: 110384b6-dad3-47a4-a3a3-f53fb5d4671e
   * Codename: bubbles
   */
  bubbles: Elements.LinkedItemsElement<BubbleModel>;

  /**
   * Format (multiple_choice)
   * Required: true
   * Id: 382e0c11-2e75-4b27-89e2-e4e6c9a0349b
   * Codename: format
   */
  format: Elements.MultipleChoiceElement;
}> &
  ColorVariant;
