import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CaseStudyModel } from './CaseStudyModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Featured customer success stories
 * Id: b8d0b321-e62d-440b-b52a-6e0e68b6e085
 * Codename: umlp_element___featured_customer_success_stories
 */
export type UmlpElementFeaturedCustomerSuccessStoriesModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 7ca4d68e-0cce-4a69-83ba-4e5fae1b614c
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Hide quotes (multiple_choice)
   * Required: false
   * Id: 0eb9d350-18f6-48c1-849a-5d9e116264e3
   * Codename: hide_quotes
   */
  hideQuotes: Elements.MultipleChoiceElement;

  /**
   * Success Stories (modular_content)
   * Required: true
   * Id: f736ce6a-4000-494b-ad7d-0f8c59f25f33
   * Codename: success_stories
   */
  successStories: Elements.LinkedItemsElement<CaseStudyModel>;
}>;
