import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Pill Carousel - Item
 * Id: 4b31290f-4ead-41b8-ba76-36f34eff0f49
 * Codename: umlp_element___pill_carousel___item
 */
export type UmlpElementPillCarouselItemModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: 57f2acfd-a882-44fa-a098-ce5e30d617ab
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: eb79797d-4874-4344-9325-2c0254828212
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * CTA (modular_content)
   * Required: true
   * Id: c08464cb-d452-4092-8606-518c13735d23
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;
}>;
