import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Full Width Image
 * Id: 1a5b2970-8a10-43c3-99af-770d7236218d
 * Codename: umlp_element___full_width_image
 */
export type UmlpElementFullWidthImageModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: d8e8f51e-df18-4d31-b037-e6f313602d4d
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: true
   * Id: 3d730b6c-fe29-4e0d-916e-cc4cadd04570
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Image size (multiple_choice)
   * Required: true
   * Id: 233f97c8-64d9-4fb5-a09d-3861b6d49175
   * Codename: image_size
   */
  imageSize: Elements.MultipleChoiceElement;
}>;
