import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CaseStudyModel } from './CaseStudyModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Customer Success Story Slider
 * Id: d550030d-7cb9-4d1d-9844-970d49fe4784
 * Codename: umlp_element___customer_success_story_slider
 */
export type UmlpElementCustomerSuccessStorySliderModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 8950721e-f0ff-495f-ba3c-8cd3c33d6920
   * Codename: heading
   *
   * Optional heading
   */
  heading: Elements.RichTextElement;

  /**
   * Format (multiple_choice)
   * Required: true
   * Id: d2e2d6ef-7d5e-476d-ad83-748823d6465e
   * Codename: format
   */
  format: Elements.MultipleChoiceElement;

  /**
   * Hide quotes (multiple_choice)
   * Required: false
   * Id: 249059de-a11e-4464-816a-8a8a021d1d50
   * Codename: hide_quotes
   */
  hideQuotes: Elements.MultipleChoiceElement;

  /**
   * Success stories (modular_content)
   * Required: true
   * Id: cfd44d5a-3896-41e1-89d5-cd174ae8d2a0
   * Codename: success_stories
   */
  successStories: Elements.LinkedItemsElement<CaseStudyModel>;
}>;
