import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementHeroFormModel } from './UmlpElementHeroFormModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Form Section
 * Id: efea6f26-9b70-4cc3-ad41-1f53c05ac787
 * Codename: umlp_element___form_section
 */
export type UmlpElementFormSectionModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 608316f6-6f6f-4d8f-b8c0-bfa21d85ca89
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: b6d17bf4-29db-462b-b317-9a66638ad2bc
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Form (modular_content)
   * Required: true
   * Id: 78185c23-1d2b-425f-b066-cda5d0492ff7
   * Codename: form
   */
  form: Elements.LinkedItemsElement<UmlpElementHeroFormModel>;
}>;
