import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Stats Section - Stat
 * Id: 238dc945-b90b-407c-a856-d0c1aca6f51d
 * Codename: umlp_element___stats_section___stat
 */
export type UmlpElementStatsSectionStatModel = IContentItem<{
  /**
   * Text (text)
   * Required: true
   * Id: 8ee60c1f-22c8-439d-99b0-6a32a211f4ac
   * Codename: text
   */
  text: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: true
   * Id: 70a279f8-2844-4ea1-a913-b50b2367bf3b
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Arrow (multiple_choice)
   * Required: true
   * Id: 618b516e-f273-4ef6-b584-b9eca63b80ac
   * Codename: arrow
   */
  arrow: Elements.MultipleChoiceElement;
}>;
