import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementRichtextCardModel } from './UmlpElementRichtextCardModel';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - RichText Card Section
 * Id: 4185476c-5502-42cc-aa0f-337cd9a0b522
 * Codename: umlp_element___richtext_card_section
 */
export type UmlpElementRichtextCardSectionModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 0450c22d-46b1-431e-a0ed-7faa83551d2c
   * Codename: heading
   *
   * Optional heading
   */
  heading: Elements.RichTextElement;

  /**
   * Cards (modular_content)
   * Required: true
   * Id: 82c05039-d0fe-4921-9eb5-37fde7f21f0d
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<UmlpElementRichtextCardModel>;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 2f07c631-40f6-4b0c-81a4-bceda4b3af86
   * Codename: cta
   *
   * Optional CTA
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Format (multiple_choice)
   * Required: false
   * Id: 8b6220f9-dd16-4dbe-a956-490f03933013
   * Codename: format
   *
   * Pick between 2 or 3 column layout
   */
  format: Elements.MultipleChoiceElement;
}>;
