import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PricingPageFaqCategoryModel } from './PricingPageFaqCategoryModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - FAQ with Categories
 * Id: 8e8b0f08-13db-4748-a173-3935c04e3997
 * Codename: umlp_element___faq_with_categories
 */
export type UmlpElementFaqWithCategoriesModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 86d44fcc-6825-4294-8935-fb3404db4aa1
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * FAQ Categories (modular_content)
   * Required: true
   * Id: 065700a6-fc01-4fb7-b471-e234a791adf6
   * Codename: faq_categories
   */
  faqCategories: Elements.LinkedItemsElement<PricingPageFaqCategoryModel>;
}>;
