import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SolutionsPageRelatedAssetModel } from './SolutionsPageRelatedAssetModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Related resources
 * Id: 2cfa45b4-8743-4a20-80f7-409e82b57c11
 * Codename: umlp_element___related_resources
 */
export type UmlpElementRelatedResourcesModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: d1a565c6-0781-4889-a4e7-0f94140ed35a
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Resources (modular_content)
   * Required: true
   * Id: 2662145a-7e30-4b57-917f-2bb471ebd4e4
   * Codename: resources
   */
  resources: Elements.LinkedItemsElement<SolutionsPageRelatedAssetModel>;

  /**
   * Hide dates on cards (multiple_choice)
   * Required: true
   * Id: d4b7bb5e-29b2-43d1-af8e-03ad578942c5
   * Codename: hide_dates_on_cards
   */
  hideDatesOnCards: Elements.MultipleChoiceElement;
}>;
