import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementAnimatedVerticalSliderSlideModel } from './UmlpElementAnimatedVerticalSliderSlideModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Animated Vertical Slider
 * Id: 72be5c3a-ad64-4989-9919-e4ffaaa37da7
 * Codename: umlp_element___animated_vertical_slider
 */
export type UmlpElementAnimatedVerticalSliderModel = IContentItem<{
  /**
   * Slides (modular_content)
   * Required: true
   * Id: 4b7217ca-fd05-4cb2-833a-320b27b5b0d2
   * Codename: slides
   */
  slides: Elements.LinkedItemsElement<UmlpElementAnimatedVerticalSliderSlideModel>;
}>;
