import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Image Carousel - Slide
 * Id: cb840ceb-dd10-419d-a7ca-835534d3b587
 * Codename: umlp_element___image_carousel___slide
 */
export type UmlpElementImageCarouselSlideModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: true
   * Id: 9620f33f-cf54-4f13-b9f3-6f429e6830a0
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: ceb042bd-4a5d-4dc0-999c-0acdf2b59915
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: true
   * Id: 77e255b7-1e8c-406c-8e9e-0be38b3f5f0d
   * Codename: image
   */
  image: Elements.AssetsElement;
}>;
