import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ComponentTimelineSliderSlideModel } from './ComponentTimelineSliderSlideModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Timeline slider
 * Id: c28a3a3e-5c02-4aad-a3d9-aff130e218cd
 * Codename: umlp_element___timeline_slider
 */
export type UmlpElementTimelineSliderModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 2f8feb37-4e2a-4651-be67-ab92fb686ab2
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Slides (modular_content)
   * Required: true
   * Id: e187d1a0-e29b-4a0e-95d5-5a9b0cc2e5ac
   * Codename: slides
   *
   * Slide cards. If you need less than 4 slides, maybe reconsider whether or not this element is the best solution for your use case.
   */
  slides: Elements.LinkedItemsElement<ComponentTimelineSliderSlideModel>;
}>;
