import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementExpandableGridRowModel } from './UmlpElementExpandableGridRowModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Expandable Grid
 * Id: af695d3e-d1fb-4fe5-8113-8ce8a7f9a0a1
 * Codename: umlp_element___expandable_grid
 */
export type UmlpElementExpandableGridModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: bbfc86d0-2e7b-498b-9d0c-a20b83c50e0d
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Rows (modular_content)
   * Required: true
   * Id: ca60776d-4bde-47ee-b964-b964f5a8bf5e
   * Codename: rows
   */
  rows: Elements.LinkedItemsElement<UmlpElementExpandableGridRowModel>;
}>;
