import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Animated Vertical Slider - Slide
 * Id: 33bde678-f75e-4cc2-86ed-a4864d123b28
 * Codename: umlp_element___animated_vertical_slider___slide
 */
export type UmlpElementAnimatedVerticalSliderSlideModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: true
   * Id: d0f81a66-aa74-4d38-af14-cb9d4695c5fc
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: d0ed1bea-2985-4e18-b042-292ba7bac3a0
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: true
   * Id: 12aa715f-b7a7-45cb-bdb3-d3796ab3e86b
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 52bf75ba-816c-475c-8d7b-25fb5cebc3e2
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;
}>;
