import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { OfficeModel } from './OfficeModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Office locations info
 * Id: a3da0f10-2832-42de-b702-e8b8ef6c7848
 * Codename: umlp_element___office_locations_info
 */
export type UmlpElementOfficeLocationsInfoModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 8c17f5c2-fbf9-49c2-abc5-00f70103790b
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Offices (modular_content)
   * Required: true
   * Id: 2cc0afb5-c73e-4a7a-8169-15d420bcae12
   * Codename: offices
   */
  offices: Elements.LinkedItemsElement<OfficeModel>;
}>;
