import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementExpandableGridCellModel } from './UmlpElementExpandableGridCellModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Expandable Grid - Row
 * Id: 60ecde85-6188-4c6e-b0ed-39cc7d8c804a
 * Codename: umlp_element___expandable_grid___row
 */
export type UmlpElementExpandableGridRowModel = IContentItem<{
  /**
   * Label (text)
   * Required: true
   * Id: 05d5498f-d74c-4e8d-afcc-7302925ec6d0
   * Codename: label
   */
  label: Elements.TextElement;

  /**
   * Cells (modular_content)
   * Required: true
   * Id: d4827781-7829-49c7-995f-1fda482d5b46
   * Codename: cells
   */
  cells: Elements.LinkedItemsElement<UmlpElementExpandableGridCellModel>;
}>;
