import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { LogoModel } from './LogoModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP Element - Logos Custom
 * Id: 5204a6b9-9229-4b0e-b9e0-418a78b7f0c9
 * Codename: umlp_element___logos_custom
 */
export type UmlpElementLogosCustomModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 33d90825-0c7d-419d-8659-635226cfbdaa
   * Codename: heading__rich
   */
  headingRich: Elements.RichTextElement;

  /**
   * Smaller heading (multiple_choice)
   * Required: false
   * Id: ed6dabfc-8ef0-4ccf-9b8c-6bd596bac1ca
   * Codename: smaller_heading
   *
   * Smaller 22px heading (default is 44px - standard h2)
   */
  smallerHeading: Elements.MultipleChoiceElement;

  /**
   * Smaller indent (multiple_choice)
   * Required: false
   * Id: 86d0cbd1-a413-4fa4-8588-d240c92b312b
   * Codename: smaller_indent
   *
   * Decreases the space between the slider and the previous section from the standard 200 or so px to 120px
   */
  smallerIndent: Elements.MultipleChoiceElement;

  /**
   * Logo size (multiple_choice)
   * Required: true
   * Id: a003af48-d3fd-49db-ab4f-458dbeaa0a13
   * Codename: logo_size
   */
  logoSize: Elements.MultipleChoiceElement;

  /**
   * Logos (modular_content)
   * Required: true
   * Id: fd5d5b1f-312a-4265-a9cd-b6e8ce61cdf2
   * Codename: logos
   */
  logos: Elements.LinkedItemsElement<LogoModel>;
}>;
