import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementPillCarouselItemModel } from './UmlpElementPillCarouselItemModel';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Pill Carousel
 * Id: e6f5089d-8730-41ca-96e2-0006bc07744e
 * Codename: umlp_element___pill_carousel
 */
export type UmlpElementPillCarouselModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: true
   * Id: ecc2be01-f9c3-4b41-9508-301673177df4
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Elements (modular_content)
   * Required: true
   * Id: 0ef898a2-cace-445f-81f7-9a84d8bd1169
   * Codename: elements
   */
  elements: Elements.LinkedItemsElement<UmlpElementPillCarouselItemModel>;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 9a7e919b-1390-4881-815d-bdb14e4c297f
   * Codename: cta
   *
   * Optional CTA
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;
}>;
