import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpElementHorizontalCardCarouselCardModel } from './UmlpElementHorizontalCardCarouselCardModel';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Horizontal Card Carousel
 * Id: 76a9e49a-9e21-404e-a56a-4a9e161f4256
 * Codename: umlp_element___horizontal_card_carousel
 */
export type UmlpElementHorizontalCardCarouselModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: true
   * Id: ffd3c549-a4d8-4e7f-8f18-67bdabf3f13e
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Carousel items (modular_content)
   * Required: true
   * Id: f025ed73-dbf3-4455-83d6-3fedadb22ec9
   * Codename: carousel_items
   */
  carouselItems: Elements.LinkedItemsElement<UmlpElementHorizontalCardCarouselCardModel>;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 28356f5e-d102-4863-a934-84756e1599ab
   * Codename: cta
   *
   * Optional CTA
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;
}>;
