import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PricingPlanCardComponentModel } from './PricingPlanCardComponentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Feature Checklist
 * Id: fd25f35d-df9e-4866-97ab-59ba9e16ee7c
 * Codename: umlp_element___pricing_hero_section_with_table
 */
export type UmlpElementPricingHeroSectionWithTableModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: true
   * Id: 964100ad-96aa-4cf1-b50f-72505b9cc02b
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Subheading (rich_text)
   * Required: false
   * Id: 99417ccd-0325-4bd0-9ab5-e6dfbd1e1935
   * Codename: subheading
   */
  subheading: Elements.RichTextElement;

  /**
   * Plans (modular_content)
   * Required: true
   * Id: 2a1cc790-d37f-4248-b2de-ac918bb2efa1
   * Codename: plans
   */
  plans: Elements.LinkedItemsElement<PricingPlanCardComponentModel>;
}>;
